### PR TITLE
Create values-de

### PR DESCRIPTION
**Pull request by Henry2o1o**

### CODE REVIEW

**Comment by Henry2o1o** [comment]
First translated with Google.
Improvements will follow.

**Comment by ThirtyDegreesRay** [comment]
@Henry2o1o Hi, thanks for your contribution first, I'am glad that you can help OpenHub translate to german, look forward to your follow Improvements.

**Comment by ThirtyDegreesRay** [comment]
I have seen your commits, there are some problems with file locations.
At fisrt, you should create folder "values-de" at [/app/src/main/res/](https://github.com/ThirtyDegreesRay/OpenHub/tree/master/app/src/main/res), then create file "strings.xml" at folder "values-de",  you can add german translation here.
For example, [chinese translations](https://github.com/ThirtyDegreesRay/OpenHub/tree/master/app/src/main/res/values-zh-rCN).

**Comment by Henry2o1o** [comment]
Okay, sorry.
I changed it.

**Comment by ThirtyDegreesRay** [comment]
It doesn't matter, but there does't have any new file!

**Comment by Henry2o1o** [comment]
I don't know why, but now it worked.

**Comment by ThirtyDegreesRay** [comment]
I had merge your pull request, and removed some strings which can't be translated.

All the app strings you can see at [/app/src/main/res/values/strings.xml](https://github.com/ThirtyDegreesRay/OpenHub/blob/master/app/src/main/res/values/strings.xml), some strings marked "translatable="false"", meaning it can't be translated. If there are any new strings needed in app, I will add it at the end of file.

Becuase of machine translation was unintelligible in some words, I hope you can checked the german translation when you have time, I will release it after you checked.

**Pull request merged**
