### PR TITLE
fix trending repositories

### PR DESCRIPTION
**Pull request by christophegrall**

### CODE REVIEW

**Comment by JoanVC100** [comment]
If you want, you can merge this fixes in my fork. I'm trying to help to this project but the author seems to not be available for merging- That way we can do the development without worrying about merging. What do you think?

https://github.com/JoanVC100/OpenHub

**Comment by christophegrall** [comment]
Done. Can you add me as collaborator on your fork ?

**Comment by christophegrall** [comment]
@JoanVC100 Can you add me as collaborator in the your project ?

**Comment by JoanVC100** [comment]
I prefer to mantain the repository like that. I like to review the changes before pushing to the repository, sorry.

**Comment by christophegrall** [comment]
https://github.com/christophegrall/OpenHub/releases/tag/v3.0.1-alpha

**Pull request closed without merging**
