### PR TITLE
reconfigure project to be much more simple, update a lot of dependencies, etc

### PR DESCRIPTION
**Pull request by TacoTheDank**
#### General
- add abi x86-64 and delete armeabi (which is obsolete)
- fix some english in README
- unclutter and simplify build.gradle files (defining versions in a file (that really isn't even meant for defining) when most of them are for only one implementation is honestly pretty pointless and just clutters the files, plus there were some that were super old and not used anymore (like retrolambda))
- set encoding utf-8
- rename daogenerator folder "thirtydereesray" to "thirtydegreesray"

#### Dependency updates (new versions are commented out next to dependency)
- bump gradle 4.6 -> 4.10.3
- novoda gradle plugin 0.3 -> 0.4.1
- test espresso 2.2.2 -> 3.0.2
- android support libraries 25.4.0 -> 2.8.0.0
- constraint-layout 1.0.2 -> 1.1.3
- (commented out) multidex 1.0.2 -> 1.0.3
- eventbus 3.0.0 -> 3.1.1
- dagger 2.11 -> 2.14.1
- (commented out) okhttp 3.6.0 -> 3.12.0
- (commented out) fastjson 1.1.46.android -> 1.1.70.android
- circleimageview 2.1.0 -> 2.2.0
- toasty 1.2.5 -> 1.3.0
- material about library 2.2.1 -> 2.2.3
- submit button 1.1.2 -> 1.1.3
- material dialog 0.9.4.5 -> 0.9.6.0
- bugly aar file 1.3.4 -> 1.3.6
- logger 2.1.1 -> 2.2.0
- jsoup 1.11.2 -> 1.11.3

you should really update rxjava; the ones you are using are soooo old :/
(and glide, dagger, and retrofit too while you're at it)

Signed-off-by: TacoTheDank <SkytkRSfan3895@gmail.com>

### CODE REVIEW

**Comment by ThirtyDegreesRay** [comment]
@TacoTheDank Hi, thank you for your PR first. And then, let's check the list.

> add abi x86-64 and delete armeabi (which is obsolete)

I agree that remove armeabi, but don't add abi x86_64 and arm64-v8a, beacuse it make app be larger. And abi x86 can run in cpu x86 and x86_64.

> fix some english in README

README should't be changed.

> unclutter and simplify build.gradle files (defining versions in a file (that really isn't even meant for defining) when most of them are for only one implementation is honestly pretty pointless and just clutters the files, plus there were some that were super old and not used anymore (like retrolambda))

It's agree that some dependencies is outdated, becuase I was busy this year, I wiil updated and test.
But please don't remove the the defining in 'gradle.properties',  although most of them are for only one implementation, beacuse this is my code format, for furture scalability.

> set encoding utf-8
rename daogenerator folder "thirtydereesray" to "thirtydegreesray"

Agree.

> app/libs/bugly_crashreport_upgrade-1.3.6.aar

The size of new version is small, but we should remove **"android.permission.READ_PHONE_STATE"** permission in AndroidManifest.xml. Because this is privacy permission, which will make publish to Google Play Store difficult.

And, where did you find version 1.3.6, the latest version in official website is 1.3.5.

**Comment by ThirtyDegreesRay** [comment]
@TacoTheDank Sorry about I can't merge this pull request directly, some files should't be changed.
I will change my local code and push to master branch.
Thank you and I will add you to contributions list.

**Comment by niihelium** [comment]
Why not use any build architecture and use split builds, or even bundled build?

**Comment by TacoTheDank** [comment]
The main problem I had with the current setup you were using is that it felt like such an unnecessary pain to manually go back and forth between the gradle properties file and the build.gradle, nevermind the readability of said properties. I find it much much easier to just define everything in the module's build.gradle file (or sometimes the root build.gradle file if there are multiple modules, as in this project's case).

I use "mvnrepository" for searching for libraries (and if they aren't listed there (which is not often), I just copy-paste into google and it shows up) https://mvnrepository.com/artifact/com.tencent.bugly/crashreport_upgrade

What I can do is just undo the commits, make the changes you suggested, and then re-commit them. No need to make another pull request.

**Pull request closed without merging**
